/**
 * Vendored, byte-compatible port of `@notesnook/theme`'s `themeToCSS` +
 * `buildVariants` + `colorsToCSSVariables` + `deriveShadeColor` (upstream
 * `dist/index.mjs:1196-1261`).
 *
 * Vendored (rather than imported) because `@notesnook/theme` ships with no
 * `sideEffects` field, so importing its runtime would pull React + theme-ui +
 * zustand into the Vue renderer bundle. We import only the *type*
 * `ThemeDefinition` (erased at build) and re-implement the CSS generation here.
 * The built-in default themes (`ThemeDark`/`ThemeLight`) come from `./defaults`
 * (also vendored, generated by `scripts/extract-default-themes.mjs`).
 *
 * Output format (the upstream theme contract):
 *   .theme-scope-<scope>-<variant> { --<color>[-<variant>]: <value>; … }
 *   .theme-scope-<scope> { …all variants inline… }
 * Primary variant uses the bare `--<color>` name; other variants append
 * `-<variant>`. A synthetic `static` variant carries `StaticColors` as
 * `--<name>-static` vars.
 */
import type { VueTheme, ThemeScopes, PartialVariants } from "./types";
import { ThemeDark, ThemeLight } from "./defaults";

/** Upstream runtime order (NOT the d.ts declaration order). */
export const THEME_SCOPES = [
  "base",
  "statusBar",
  "list",
  "editor",
  "editorToolbar",
  "editorSidebar",
  "titleBar",
  "dialog",
  "navigationMenu",
  "contextMenu",
  "sheet"
] as const satisfies readonly (keyof ThemeScopes)[];

export const Variants = [
  "primary",
  "secondary",
  "disabled",
  "selected",
  "error",
  "success"
] as const;

export const StaticColors = {
  red: "#f44336",
  orange: "#FF9800",
  yellow: "#FFD600",
  green: "#4CAF50",
  blue: "#2196F3",
  purple: "#673AB7",
  gray: "#9E9E9E",
  black: "#000000",
  white: "#ffffff"
} as const;

export type ScopeKey = (typeof THEME_SCOPES)[number];
export type VariantKey = (typeof Variants)[number];
type ColorMap = Record<string, string>;
type VariantMap = Record<string, ColorMap>;
type ResolvedVariants = VariantMap;

/**
 * Port of upstream `tinycolor2`'s `setAlpha(0.1).toHex8String()`.
 * Input is an accent color (RGB hex, 3 or 6 digits); output `#RRGGBBAA` with
 * alpha = round(0.1 * 255) = 26 = 0x1A, lowercased.
 */
export function deriveShadeColor(color: string): string {
  const hex = color.replace(/^#/, "");
  const full =
    hex.length === 3
      ? hex
          .split("")
          .map((c) => c + c)
          .join("")
      : hex.length === 6
        ? hex
        : hex.slice(0, 6);
  return `#${full.toLowerCase()}1a`;
}

/** Verbatim: emits `--<color>[-<variant>]: <value>;\n` per color (insertion order). */
export function colorsToCSSVariables(colors: ColorMap, variantKey: string): string {
  let root = "";
  const suffix = !variantKey || variantKey === "primary" ? "" : `-${variantKey}`;
  for (const color in colors) {
    root += `--${color}${suffix}: ${colors[color]};\n`;
  }
  return root;
}

/**
 * Resolve the full variant set for a scope, with the upstream fallback chain:
 * `themeScope[variant][color] || theme.scopes.base[variant][color] ||
 *  defaultThemeScope[variant][color] || defaultThemeBase[variant][color]`.
 * `defaultTheme` is `ThemeDark`/`ThemeLight` by `colorScheme`. Each variant's
 * `shade` is derived from its resolved `accent`.
 */
export function buildVariants(
  scope: ScopeKey,
  theme: VueTheme,
  themeScopeRaw: PartialVariants | undefined
): ResolvedVariants {
  const defaultTheme = theme.colorScheme === "dark" ? ThemeDark : ThemeLight;
  const defaultThemeBase = defaultTheme.scopes.base as unknown as VariantMap;
  const defaultThemeScope = (defaultTheme.scopes[scope] ?? {}) as unknown as VariantMap;
  const themeBase = theme.scopes.base as unknown as VariantMap;
  const themeScope = (themeScopeRaw ?? {}) as unknown as VariantMap;

  const getColor = (variant: string, color: string): string =>
    (themeScope[variant]?.[color] ??
      themeBase[variant]?.[color] ??
      defaultThemeScope[variant]?.[color] ??
      defaultThemeBase[variant]?.[color]) as string;

  const merge = (variant: string): ColorMap => {
    const base: ColorMap = {
      ...(defaultThemeBase[variant] as ColorMap | undefined),
      ...(defaultThemeScope[variant] as ColorMap | undefined),
      ...(themeBase[variant] as ColorMap | undefined),
      ...(themeScope[variant] as ColorMap | undefined)
    };
    return { ...base, shade: deriveShadeColor(getColor(variant, "accent")) };
  };

  // Key order matches upstream: defaultThemeBase spread (primary, secondary,
  // disabled, selected, error, success), then `static` appended.
  return {
    primary: merge("primary"),
    secondary: merge("secondary"),
    disabled: merge("disabled"),
    selected: merge("selected"),
    error: merge("error"),
    success: merge("success"),
    static: { ...StaticColors }
  } satisfies ResolvedVariants as ResolvedVariants;
}

/** Verbatim port. Returns the full theme CSS (all scopes, all variants). */
export function themeToCSS(theme: VueTheme): string {
  const css: string[] = [];
  for (const scopeKey of THEME_SCOPES) {
    const themeScope = theme.scopes[scopeKey];
    const variants = buildVariants(scopeKey, theme, themeScope);
    let scopeCss = `.theme-scope-${scopeKey} {\n\t`;
    for (const variantKey in variants) {
      const variant = variants[variantKey];
      if (!variant) continue;
      css.push(
        `.theme-scope-${scopeKey}-${variantKey} {\n          ${colorsToCSSVariables(
          variant,
          variantKey
        )}\n        }`
      );
      scopeCss += colorsToCSSVariables(variant, variantKey);
      scopeCss += "\n\n";
    }
    scopeCss += "}";
    css.push(scopeCss);
  }
  return css.join("\n\n");
}