/**
 * DO NOT EDIT — generated by `scripts/gen-production-hosts.mjs` from the
 * upstream `hosts` production branch in
 * `vendor/notesnook/packages/core/src/utils/constants.ts`.
 *
 * Regenerate after bumping the upstream submodule:
 *   npm run gen:hosts        # or: node scripts/build-vendor.mjs (calls it)
 *
 * Why this exists: core's `hosts` picks its values via `isProduction()`
 * (`process.env.NODE_ENV === "production" || === "test"`), so in `npm run
 * dev` (Vite statically defines `process.env.NODE_ENV` as `"development"` in
 * the renderer — a build-time literal that can't be overridden at runtime)
 * every default host collapses to `http://localhost:…`. Extracting the
 * production URLs from the upstream source at vendor-build time keeps the
 * "Notesnook (default)" profile pointing at the real servers in dev without
 * hand-maintaining URLs here. A contract test pins this to core's runtime
 * `hosts` (equal under `NODE_ENV=test`) so a stale regen fails CI loudly.
 */
import { hosts } from "@notesnook-vue/contracts";

type Hosts = typeof hosts;

export const PRODUCTION_HOSTS: Hosts = {
  API_HOST: "https://api.notesnook.com",
  AUTH_HOST: "https://auth.streetwriters.co",
  SSE_HOST: "https://events.streetwriters.co",
  SUBSCRIPTIONS_HOST: "https://subscriptions.streetwriters.co",
  ISSUES_HOST: "https://issues.streetwriters.co",
  MONOGRAPH_HOST: "https://monogr.ph",
  NOTESNOOK_HOST: "https://notesnook.com"
};
