/**
 * ⚠️ GENERATED by `scripts/gen-upstream-baseline.mjs` — do not edit by hand.
 * Regenerate after every `vendor/notesnook` submodule bump:
 *   npm run gen:upstream-baseline   (or `node scripts/build-vendor.mjs`)
 *
 * Records the upstream release we "developed against": the newest GitHub
 * release tag that is an ancestor of (or equal to) our pinned submodule
 * commit. The desktop app compares this against the latest release fetched
 * at runtime to decide whether to notify the user of a newer upstream
 * release (see `apps/desktop/src/main/upstream-checker.ts`).
 *
 * Committed so CI / `npm install` / `npm run dev` work without the submodule
 * checked out or network access.
 */
export interface UpstreamBaseline {
  /** GitHub `owner/repo` of the vendored upstream. */
  repo: string;
  /** The release tag we developed against (e.g. `v3.4.4`). */
  baselineTag: string;
  /** ISO publish time of the baseline release, if known. */
  baselinePublishedAt: string | null;
  /** The pinned `vendor/notesnook` submodule commit this baseline was derived from. */
  pinnedSha: string;
}

export const UPSTREAM_BASELINE: UpstreamBaseline = {
  repo: "streetwriters/notesnook",
  baselineTag: "v3.4.5",
  baselinePublishedAt: "2026-07-28T16:19:40Z",
  pinnedSha: "b5140d9947d01d34635d5e8b1d4653bea26a73a7"
};
